### ISSUE TITLE
[client/catapult] Testnet node stopped syncing from block 588857

### ISSUE THREAD

**Issue by sokiaoba** [symbol/symbol#355] opened 2022-08-03 12:10 UTC
### System Information

- Client Version: gcc-10-1.0.3.3
- REST Version: 2.4.0
- Operating System / Installed With / VPS Provider
  - We are running docker image (downloaded from https://hub.docker.com/r/symbolplatform/symbol-server) on k8s (GKE)
- Are you fully synchronized?: No (synced until block 588857)
- Did you try to restart your node?: Yes

#### Description

- expected
Testnet node continues to sync without interruption.

- actual
Testnet node stopped syncing from block 588857.

#### Steps to Reproduce

Unknown

#### Logs

```
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:44.420886 0x00007f48b0ff9700: <warning> (consumers::BlockchainProcessor.cpp@221) block state hash (A7E9C0F72C886E22511D8B54758EEAFA62D144A978305EE75779B53172687E17) does not match cache state hash (D00AB84A9D6D8F528FDD68CA76ABD4A96B10AAB5EEC7975C34C183000C43AB04) at height 588857
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:44.420928 0x00007f48b0ff9700: <info> (consumers::BlockchainProcessor.cpp@227) cache state hash (9 components) at height 588856
symbol-testnet-1-node-859b86c7f5-787s5 server A7E9C0F72C886E22511D8B54758EEAFA62D144A978305EE75779B53172687E17
symbol-testnet-1-node-859b86c7f5-787s5 server  + 69E48C7FB749A28308B41CFA125F488156630F23D478CAB29A481F7389DF4640
symbol-testnet-1-node-859b86c7f5-787s5 server  + B829A3813367F5E8AEC758A3ABCDD705331E695A18ACF27831668BB86CE4896E
symbol-testnet-1-node-859b86c7f5-787s5 server  + 5A5C7B39D95C9E0CCE79268C9802AC9D43A1E09A6C6C6D7BBC77199EB4C2DB2F
symbol-testnet-1-node-859b86c7f5-787s5 server  + 31F8F02F965A74E944E6E16612D6EEA051235C03F3E32E980EB279C12C95BF81
symbol-testnet-1-node-859b86c7f5-787s5 server  + 6725FF220ADA1BDCB8471C0A0ED974EED24B7551686D4AEECCF521402A0200F1
symbol-testnet-1-node-859b86c7f5-787s5 server  + 7786D39E25D978EFB75FDCE5F6303FDA44F41AA727DD27BDBF7B218E4396E209
symbol-testnet-1-node-859b86c7f5-787s5 server  + 9193E9F30A1EECE1BF671C91BBA494A25259A60023BFBBDBD44E21A74936E7D7
symbol-testnet-1-node-859b86c7f5-787s5 server  + 244CD3D37E742FEAA8B8F9DBE6A9E4859E60FB398DC0074B854ED33D97F0D67F
symbol-testnet-1-node-859b86c7f5-787s5 server  + 4013FF9603AB57ACA37FCD58169A2DF93BD476084DF66AFDCF369E1FD6EE0472
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:44.420933 0x00007f48b0ff9700: <info> (consumers::BlockchainProcessor.cpp@227) cache state hash (9 components) at height 588857
symbol-testnet-1-node-859b86c7f5-787s5 server D00AB84A9D6D8F528FDD68CA76ABD4A96B10AAB5EEC7975C34C183000C43AB04
symbol-testnet-1-node-859b86c7f5-787s5 server  + 2A9317E1ED6FDC8A8F56FF92E7D72993B230E700032010E4238C52CF9B8C66D3
symbol-testnet-1-node-859b86c7f5-787s5 server  + B829A3813367F5E8AEC758A3ABCDD705331E695A18ACF27831668BB86CE4896E
symbol-testnet-1-node-859b86c7f5-787s5 server  + 213ED8F1CD8585ABE9DD2A89F30837D44FBC063905A0DC1481218F12B9FC0DA6
symbol-testnet-1-node-859b86c7f5-787s5 server  + 31F8F02F965A74E944E6E16612D6EEA051235C03F3E32E980EB279C12C95BF81
symbol-testnet-1-node-859b86c7f5-787s5 server  + 6725FF220ADA1BDCB8471C0A0ED974EED24B7551686D4AEECCF521402A0200F1
symbol-testnet-1-node-859b86c7f5-787s5 server  + 7786D39E25D978EFB75FDCE5F6303FDA44F41AA727DD27BDBF7B218E4396E209
symbol-testnet-1-node-859b86c7f5-787s5 server  + 9193E9F30A1EECE1BF671C91BBA494A25259A60023BFBBDBD44E21A74936E7D7
symbol-testnet-1-node-859b86c7f5-787s5 server  + 244CD3D37E742FEAA8B8F9DBE6A9E4859E60FB398DC0074B854ED33D97F0D67F
symbol-testnet-1-node-859b86c7f5-787s5 server  + 4013FF9603AB57ACA37FCD58169A2DF93BD476084DF66AFDCF369E1FD6EE0472
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:44.420942 0x00007f48b0ff9700: <warning> (consumers::BlockchainSyncConsumer.cpp@268) processing of peer chain failed with Failure_Chain_Block_Inconsistent_State_Hash
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:44.422524 0x00007f488bfff700: <info> (disruptor::ConsumerDispatcher.cpp@44) completing processing of element 2516 (360 blocks (heights 588857 - 589216) [D319FE7F] from Remote_Pull with size 135KB 788B), last consumer is 0 elements behind
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:44.422594 0x00007f488bfff700: <warning> (consumers::ReclaimMemoryInspector.cpp@33) consumer aborted at position 2515 while processing 360 blocks (heights 588857 - 589216) [D319FE7F] from Remote_Pull with size 135KB 788B due to Failure_Chain_Block_Inconsistent_State_Hash
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.505823 0x00007f49dcb89700: <warning> (net::PacketWriters.cpp@357) calling error handler due to timeout
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.505905 0x00007f49dcb89700: <warning> (net::PacketWriters.cpp@331) error handler triggered for dusanjp7 @ 7.dusan.gq:7900
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.505938 0x00007f49c5ffb700: <warning> (net::PacketWriters.cpp@357) calling error handler due to timeout
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.505970 0x00007f49927fc700: <warning> (net::PacketWriters.cpp@207) closing connection to FUKUI-TESTNET(v1.1.6) @ stg.harvesting-sweet-potatoes.club:7900 due to unexpected data
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.505995 0x00007f49ddb8b700: <warning> (net::PacketWriters.cpp@207) closing connection to dusanjp7 @ 7.dusan.gq:7900 due to unexpected data
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.506020 0x00007f49c5ffb700: <warning> (net::PacketWriters.cpp@331) error handler triggered for FUKUI-TESTNET(v1.1.6) @ stg.harvesting-sweet-potatoes.club:7900
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.506332 0x00007f49beffd700: <error> (ionet::PacketSocket.cpp@44) failed when reading from socket: Operation canceled
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.506370 0x00007f49beffd700: <warning> (net::PacketWriters.cpp@266) calling error handler due to read error (Read_Error)
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.506381 0x00007f49beffd700: <warning> (net::PacketWriters.cpp@331) error handler triggered for dusanjp7 @ 7.dusan.gq:7900
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.506391 0x00007f49beffd700: <warning> (net::PacketWriters.cpp@162) ignoring request to remove unknown socket
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.506414 0x00007f49beffd700: <error> (api::RemoteRequestDispatcher.h@50) read from remote node failed for peers info request
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.506481 0x00007f49beffd700: <warning> (src::BatchPeersRequestor.cpp@54) exception thrown while requesting peers: read from remote node failed
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.506637 0x00007f49de38c700: <error> (ionet::PacketSocket.cpp@44) failed when reading from socket: Operation canceled
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.506704 0x00007f49be7fc700: <warning> (net::PacketWriters.cpp@266) calling error handler due to read error (Read_Error)
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.506732 0x00007f49be7fc700: <warning> (net::PacketWriters.cpp@331) error handler triggered for FUKUI-TESTNET(v1.1.6) @ stg.harvesting-sweet-potatoes.club:7900
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.506744 0x00007f49be7fc700: <warning> (net::PacketWriters.cpp@162) ignoring request to remove unknown socket
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.506751 0x00007f49be7fc700: <error> (api::RemoteRequestDispatcher.h@50) read from remote node failed for peers info request
symbol-testnet-1-node-859b86c7f5-787s5 server 2022-08-03 11:36:45.506778 0x00007f49be7fc700: <warning> (src::BatchPeersRequestor.cpp@54) exception thrown while requesting peers: read from remote node failed
```

**Comment by cryptoBeliever** [comment] 2023-01-16 17:13
@sokiaoba Most probably you could not sync on default settings because of connectivity issues. 
Since testnet was reset already are you able reproduce on new testnet network?

**Comment by cryptoBeliever** [comment] 2023-04-06 17:13
I'm closing this one. Please let me know if you still need help with it. You can also join our Discord https://discord.com/invite/xymcity

**Closed by cryptoBeliever** 2023-04-06 17:13 UTC
Labels: Status: WIP, Type: Bug, catapult
