### ISSUE TITLE
[client/rest] {"apiNode":"down","db":"up"}

### ISSUE THREAD

**Issue by p1-p1** [symbol/symbol#85] opened 2022-02-01 06:33 UTC
Hi.
Cloud platform suddenly (it was my fault) shut down my instance with my node. After I returned access I tried to start node (symbol-bootstrap start --upgrade -d) , but it didn’t work out. Symbol-bootstrap healthCheck: …
```
warn     Container node is NOT running YET. 
warn     Container broker is NOT running YET.
```
I know about **symbol-bootstrap resetData** however maybe something else may fix it.
Server and broker logs are attached.
Thanks in advance.

**Comment by p1-p1** [comment] 2022-02-01 07:11
My apologies to the assigned people. It was an accident ((

**Comment by Wayonb** [comment] 2022-02-01 16:37
@p1-p1 I am not see all the logs, can you verify that all logs was included in the zip file?
For example on discord you attach the below but I dont see it in the recovery logs - https://discord.com/channels/856325968096133191/937769746399645698/937869211580137583
Maybe I am missing something.
```
!!!! Have lock file present, going to run recovery in broker mode....
Copyright (c) Jaguar0625, gimre, BloodyRookie, Tech Bureau, Corp. catapult version: 1.0.3.1 (public)
loading resources from "./broker-config/resources"
…
<info> (plugins::PluginModule.cpp@83) loading plugin from /usr/catapult/lib/libcatapult.plugins.transfer.so
<info> (utils::StackLogger.h@37) pushing scope 'running recovery operations'
<info> (recovery::RecoveryOrchestrator.cpp@149) repairing spooling, commit step 2
<info> (recovery::RecoveryOrchestrator.cpp@152) repairing importance
<info> (recovery::RecoveryOrchestrator.cpp@155) repairing messages
<info> (recovery::RecoveryOrchestrator.cpp@158) loading state
<important> (utils::StackLogger.h@37) pushing scope 'load state'
<error> (io::BufferedFileStream.cpp@88) Throwing exception: couldn't read from file, requested size vs available (8, 0)
<important> (utils::StackLogger.h@43) popping scope 'load state' (8ms)
<info> (utils::StackLogger.h@43) popping scope 'running recovery operations' (15ms)
<fatal> (local::HostUtils.h@43) unhandled exception while boot!
/catapult-src/src/catapult/io/BufferedFileStream.cpp(88): Throw in function void catapult::io::{anonymous}::ThrowReadError(size_t, size_t)
```

**Comment by Wayonb** [comment] 2022-02-01 16:39
I am not sure how your node got into this state but from the logs above, the catapult state seem invalid.  It might need to use the ``symbol-bootstrap resetData``

**Comment by p1-p1** [comment] 2022-02-02 01:49
Here is the full logs.
[logs.zip](https://github.com/symbol/symbol/files/7983041/logs.zip)
[logs2.zip](https://github.com/symbol/symbol/files/7983043/logs2.zip)

**Comment by Wayonb** [comment] 2022-02-02 03:28
@p1-p1 Thanks for the extra logs.  I am assuming the server died and was not able to recover its state.
How much memory and cores do you have on your node?

**Comment by p1-p1** [comment] 2022-02-02 04:01
2 vCPU and 8GB

**Comment by Wayonb** [comment] 2022-02-02 13:54
@p1-p1 Thanks.  Can you point me to your host provider?
My concern is with resources cause it seemed like both the broker and server died around the same time.

**Comment by p1-p1** [comment] 2022-02-02 17:36
@Wayonb Oracle Cloud

**Comment by Wayonb** [comment] 2022-02-14 15:06
Closing until the issue is reproduce.  Please reopen when the problem happens again.

**Closed by Wayonb** 2022-02-14 15:06 UTC
Labels: Status: WIP, rest
